### ISSUE TITLE
Feature request: Add ability to override PR NUMBER

### ISSUE THREAD

**Issue by jecnua** [phulsechinmay/rewritable-pr-comment#4]
Hi,

Thank you so much for the work on this action :)
I am in a situation in which would be good for me to override the PR number to work on since, well, I am not in a PR. I am working on a pipeline testing in a PUSH workflow since as far as I can see I have no way to restrict PR workflow on only the one coming for a certain branch.
I think such option could be useful also for testing purposes (in case you may want to write on an existing pr to test instead of polluting new ones every time). 
The env value to pass defaults to empty and if that's the case the behaviour is the same as now.
I hope it make sense.
Thanks for your time.

**Comment by phulsechinmay** [comment]
Hey, thanks for the feature request!

I'm not really sure that I exactly understand what you're asking for. Do you want to be able to specify a PR number for the comment, so after the workflow runs on a separate PR, the bot will edit a comment on the PR given as input to the action?

**Comment by jecnua** [comment]
Hi @phulsechinmay thank you for replying :) Basically I was asking for a way to override this:

`https://github.com/phulsechinmay/rewritable-pr-comment/blob/347f4a106261e162c241537f50112bf3b0af7705/index.js#L27`

Bein able to just pass via env a PR number to the action would be very useful for testing purposes. Usually flexibility is good (personal opinion). By defaulting to the normal behaviour would be retro-compatible. Example:

`const pr_number = core.getInput('ISSUE_ID') ? core.getInput('ISSUE_ID') : ctx.payload.pull_request.number;`

However feel free to ignore my request if maybe is just a use-case for me. ^^
Thanks for your time.

**Comment by phulsechinmay** [comment]
@jecnua Thanks for this suggestion, I really like it! Definitely extends the usability of the action. I've now added issue / PR overriding functionality, it's configurable through the workflow config itself.
